platform :ios, ‘8.0’

target ‘MarketValue’ do
	pod 'Masonry’
	pod 'MBProgressHUD'
	pod 'SDWebImage'
	pod 'SDCycleScrollView’
	pod 'IQKeyboardManager’
	pod ‘AFNetworking’
	pod 'MJRefresh'
	pod 'CYLTabBarController'
end
